=== SaadZK/PFAT/XML/XPATH+XSLT/Ejercicios/ej1.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ENTITY % PennyLane
"atr1 CDATA #IMPLIED
atr2 ID #IMPLIED" >

<!ELEMENT R (D, E)>
<!ELEMENT D EMPTY>
<!ATTLIST D %PennyLane;>
<!ELEMENT E ((A | B | C | E), (A | E))>

<!ELEMENT A EMPTY>

<!ELEMENT B EMPTY>

<!ELEMENT C (#PCDATA)>

=== SaadZK/PFAT/XML/XPATH+XSLT/Ejercicios/DOC1-EJ1.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE R SYSTEM "./ej1.dtd" >
<R>
  <D/>
  <E>
    <E>
      <A/>
      <A/>
    </E>
    <E>
      <A/>
      <A/>
    </E>
  </E>
</R>
